"""[update] Update table to include task progress

Revision ID: a5afed23deb4
Revises: 06cdf7561f62
Create Date: 2026-03-29 19:24:42.090779

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a5afed23deb4"
down_revision: Union[str, Sequence[str], None] = "06cdf7561f62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
